"""add ticket validation fields

Revision ID: f4ae2a55fe93
Revises: 6819943a19d0
Create Date: 2026-07-13 14:03:38.434497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ae2a55fe93'
down_revision: Union[str, Sequence[str], None] = '6819943a19d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tickets', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'used_at')
    op.drop_column('tickets', 'is_used')
    # ### end Alembic commands ###
